apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-service
      version: v1
      tier: experience
  template:
    metadata:
      labels:
        app: demo-service
        version: v1
        tier: experience
    spec:
      containers:
      - name: demo-service
        image: 803138993991.dkr.ecr.us-east-2.amazonaws.com/demo-service
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 8G
            cpu: 250m
          limits:
            memory: 16G
            cpu: 500m
        ports:
        - containerPort: 8080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1